### PR TITLE
Remove env PYTHONOPTIMIZE in docker image

### PR DESCRIPTION
**Pull request by wkcn**
**Description**
Remove env `PYTHONOPTIMIZE=1` in docker image since it will skip `assert 0` in python.

When env `PYTHONOPTIMIZE=1`,
```python
Python 3.8.10 (default, Nov 14 2022, 12:59:47)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> assert 0
```
No exception raises.

### CODE REVIEW

**Comment by tocean** [comment]
I got this error when training gpt3 using Megatron-LM. After `export PYTHONOPTIMIZE=0`, this error disappeared.
image

**Review by tocean — APPROVED** [review]
If there is no performance impact, LGTM.

**Review by abuccts — APPROVED** [review]
actually the goal of this env is to skip all `assert` statements in real runs..

**Comment by wkcn** [comment]
> actually the goal of this env was to skip all `assert` statements in real runs..

Users may not know `assert` statements are skipped, and some codes depend on `assert`.
For example,
```python
class Dataset:
    ...
    def __getitem__(self, idx):
        try:
            data = self.get_data()
            assert data is not None
        except:
            return self.__getitem__(idx - 1)
        return data
```

**Pull request merged**
