### PR TITLE
[Bug Fixed] Fix inf/nan weight gradient checker

### LINKED ISSUE #32: There is a down spike in curve of accuracy@1 when training vision transformer
**What's the issue, what's expected?**:
There is a down spike in the curve of acc@1 when training vision transformer. However, the curve is very smooth when using mfp8.

**How to reproduce it?**:
Train vision transformer model using MS-AMP O2 with multiple H100 GPUs.

**Log message or shapshot?**:

image

**Additional information**:

### PR DESCRIPTION
**Pull request by wkcn**
**Description**
When training a model, the function [`_amp_foreach_non_finite_check_and_unscale_`](https://github.com/Azure/MS-AMP/blob/main/msamp/common/tensor/tensor.py#L750) is called to check whether INF/NAN exists in weight gradients. For the weight gradients stored in ScalingTensor, its INF/NAN is checked by `scale_inv` and `amax[0]` (tensor.py#L790 and L795).

However, in the previous code, `amax[0]` is not synchronized across multiple GPUs. It leads to different states whether INF/NAN exists across multiple GPUs. The inconsistent behaviour drops the accuracy of model.

In this PR, I fix the bug to keep the consistence of `amax[0]` across GPUs. Here is the performance table. Fix #32 

- Validation top-1 accuracy on ImageNet-1k

Model | Device | top-1 Acc. (%)
---|---|---
DeiT-S | H100 | 79.9
Swin-T | H100 | 81.1 

Baseline: DeiT-S: 79.9, Swin-T: 81.2

**Major Revision**
- Synchronize `meta.amax[0]` rather than `meta.scale`. Since `max(NAN, 3) = 3` in NCCL AllReduce, we convert all NAN to INF before NCCL AllReduceMax.
- Create the tensor `arg_amax` to avoid `TransformerEngineWrapper.cast_to_fp8` to re-write `meta.amax[0]`.
- Set the maximum scaling factor for `cast_to_fp16`.
- re-write the update of scaling factors in `msamp/optim/optimizer.py`
- unit-test for the cast of ScalingTensor with NAN or INF.

### CODE REVIEW

**Comment by tocean** [comment]
Could you also add curve of loss and accuracy of  DeiT  model in the performance part of README.md?

**Comment by wkcn** [comment]
> Could you also add curve of loss and accuracy of DeiT model in the performance part of README.md? You can add the log and data [here](https://microsoftapc.sharepoint.com/teams/AzureCIPlatformTeam/Shared%20Documents/Forms/AllItems.aspx?id=%2Fteams%2FAzureCIPlatformTeam%2FShared%20Documents%2FMSRA%20Collaboration%2FMS%2DAMP%2Fdeit&viewid=e843ac85%2D982a%2D4e68%2D82c7%2D11e826533199)

Yes. I will update README.md in a new PR for better review. I could not access `Azure C+AI Inference Platform Team`.

**Comment by tocean** [comment]
> 
 Try again.

**Comment by tocean** [comment]
> > Could you also add curve of loss and accuracy of DeiT model in the performance part of README.md? You can add the log and data [here](https://microsoftapc.sharepoint.com/teams/AzureCIPlatformTeam/Shared%20Documents/Forms/AllItems.aspx?id=%2Fteams%2FAzureCIPlatformTeam%2FShared%20Documents%2FMSRA%20Collaboration%2FMS%2DAMP%2Fdeit&viewid=e843ac85%2D982a%2D4e68%2D82c7%2D11e826533199)
> 
> Yes. I will update README.md in a new PR for better review. I could not access `Azure C+AI Inference Platform Team`.



> > Could you also add curve of loss and accuracy of DeiT model in the performance part of README.md? You can add the log and data [here](https://microsoftapc.sharepoint.com/teams/AzureCIPlatformTeam/Shared%20Documents/Forms/AllItems.aspx?id=%2Fteams%2FAzureCIPlatformTeam%2FShared%20Documents%2FMSRA%20Collaboration%2FMS%2DAMP%2Fdeit&viewid=e843ac85%2D982a%2D4e68%2D82c7%2D11e826533199)
> 
> Yes. I will update README.md in a new PR for better review. I could not access `Azure C+AI Inference Platform Team`.

Try again.

**Comment by wkcn** [comment]
> > > Could you also add curve of loss and accuracy of DeiT model in the performance part of README.md? You can add the log and data [here](https://microsoftapc.sharepoint.com/teams/AzureCIPlatformTeam/Shared%20Documents/Forms/AllItems.aspx?id=%2Fteams%2FAzureCIPlatformTeam%2FShared%20Documents%2FMSRA%20Collaboration%2FMS%2DAMP%2Fdeit&viewid=e843ac85%2D982a%2D4e68%2D82c7%2D11e826533199)
> > 
> > 
> > Yes. I will update README.md in a new PR for better review. I could not access `Azure C+AI Inference Platform Team`.
> 
> > > Could you also add curve of loss and accuracy of DeiT model in the performance part of README.md? You can add the log and data [here](https://microsoftapc.sharepoint.com/teams/AzureCIPlatformTeam/Shared%20Documents/Forms/AllItems.aspx?id=%2Fteams%2FAzureCIPlatformTeam%2FShared%20Documents%2FMSRA%20Collaboration%2FMS%2DAMP%2Fdeit&viewid=e843ac85%2D982a%2D4e68%2D82c7%2D11e826533199)
> > 
> > 
> > Yes. I will update README.md in a new PR for better review. I could not access `Azure C+AI Inference Platform Team`.
> 
> Try again.

I can access it now.

**Review by tocean — APPROVED** [review]
LGTM

**Review by guoshzhao — APPROVED** [review]

**Pull request merged**
